# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2022, WANG Hailin
# This file is distributed under the same license as the abqpy package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: abqpy \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-27 13:50+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.12.1\n"

#: ../../reference/mdb/model/profile.md:1
msgid "Beam Section Profile"
msgstr ""

#: ../../reference/mdb/model/profile.md:3
msgid ""
"The Beam Section profile commands are used to create profiles. A profile "
"definition specifies the properties of a beam that are related to its "
"cross-section geometry. When you define a beam section, you must include a"
" reference to a profile in the section definition."
msgstr ""

#: ../../reference/mdb/model/profile.md:5
msgid "Create beam section profiles"
msgstr ""

#: ../../reference/mdb/model/profile.md:7
msgid "In Mdb"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:1
#: of
msgid "Bases: :py:class:`~abaqus.Model.ModelBase.ModelBase`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:1
#: of
msgid ""
"Abaqus creates a Model object named `Model-1` when a session is started."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:5
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:4
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:5
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:5
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:6
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:5
#: abaqus.BeamSectionProfile.IProfile.IProfile:5
#: abaqus.BeamSectionProfile.LProfile.LProfile:5
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:5
#: abaqus.BeamSectionProfile.Profile.Profile:5
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:5
#: abaqus.BeamSectionProfile.TProfile.TProfile:5
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:5 of
msgid "This object can be accessed by::"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:9
#: of
msgid ""
"Check `BeamSectionProfileModel on help.3ds.com/2016 <https://help.3ds.com/"
"2016/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"modelpyc.htm?contextscope=all>`__."
msgstr ""

#: ../../None:7:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:11
#: of
msgid "This method creates a Model object."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:34
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:14
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:5
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:4
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:4
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:22
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:22
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:23
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:22
#: abaqus.BeamSectionProfile.IProfile.IProfile:22
#: abaqus.BeamSectionProfile.LProfile.LProfile:22
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:22
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:5
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:22
#: abaqus.BeamSectionProfile.TProfile.TProfile:22
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:22 of
msgid "This function can be accessed by::"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile
#: abaqus.BeamSectionProfile.IProfile.IProfile
#: abaqus.BeamSectionProfile.LProfile.LProfile
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile
#: abaqus.BeamSectionProfile.TProfile.TProfile
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile of
msgid "Parameters"
msgstr ""

#: ../../None:52:<autosummary>:1 ../../docstring
#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:40
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:19
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:20
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:13
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:13
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:28
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:28
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:29
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:28
#: abaqus.BeamSectionProfile.IProfile.IProfile:28
#: abaqus.BeamSectionProfile.LProfile.LProfile:28
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:28
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:28
#: abaqus.BeamSectionProfile.TProfile.TProfile:28
#: abaqus.BeamSectionProfile.TrapezoidalProfile.Profile.name:1
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:28 of
msgid "A String specifying the repository key."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:21
#: of
msgid ""
"A String specifying the purpose and contents of the Model object. The "
"default value is an empty string."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:24
#: of
msgid ""
"None or a Float specifying the Stefan-Boltzmann constant. The default "
"value is None."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:26
#: of
msgid ""
"None or a Float specifying the absolute zero constant. The default value "
"is None."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:28
#: of
msgid ""
"A SymbolicConstant specifying the type of incident wave formulation to be "
"used in acoustic problems. Possible values are NOT_SET, SCATTERED, and "
"TOTAL. The default value is NOT_SET."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:32
#: of
msgid ""
"A SymbolicConstant specifying the analysis model type. Possible values are"
" STANDARD_EXPLICIT and ELECTROMAGNETIC. The default is STANDARD_EXPLICIT."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:35
#: of
msgid ""
"None or a Float specifying the universal gas constant. The default value "
"is None."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:37
#: of
msgid ""
"A boolean specifying whether to copy the constraints created in the model "
"to the model that instances this model. The default value is ON."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:40
#: of
msgid ""
"A boolean specifying whether to copy the connectors created in the model "
"to the model that instances this model. The default value is ON."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:43
#: of
msgid ""
"A boolean specifying whether to copy the interactions created in the model"
" to the model that instances this model. The default value is ON."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile
#: abaqus.BeamSectionProfile.IProfile.IProfile
#: abaqus.BeamSectionProfile.LProfile.LProfile
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile
#: abaqus.BeamSectionProfile.TProfile.TProfile
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile of
msgid "Returns"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:46
#: of
msgid "A Model object."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile
#: abaqus.BeamSectionProfile.IProfile.IProfile
#: abaqus.BeamSectionProfile.LProfile.LProfile
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile
#: abaqus.BeamSectionProfile.TProfile.TProfile
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile of
msgid "Return type"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:47
#: of
msgid ":class:`Model`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb of
msgid "Public Data Attributes:"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`name <abaqus.Model.ModelBase.ModelBase.name>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`stefanBoltzmann "
"<abaqus.Model.ModelBase.ModelBase.stefanBoltzmann>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "None or a Float specifying the Stefan-Boltzmann constant."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`absoluteZero <abaqus.Model.ModelBase.ModelBase.absoluteZero>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "None or a Float specifying the absolute zero constant."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`waveFormulation "
"<abaqus.Model.ModelBase.ModelBase.waveFormulation>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A SymbolicConstant specifying the type of incident wave formulation to be "
"used in acoustic problems."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`universalGas <abaqus.Model.ModelBase.ModelBase.universalGas>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "None or a Float specifying the universal gas constant."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`noPartsInputFile "
"<abaqus.Model.ModelBase.ModelBase.noPartsInputFile>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A Boolean specifying whether an input file should be written without parts"
" and assemblies."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`restartIncrement "
"<abaqus.Model.ModelBase.ModelBase.restartIncrement>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"An Int specifying the increment, interval, iteration or cycle where the "
"restart analysis will start."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`endRestartStep "
"<abaqus.Model.ModelBase.ModelBase.endRestartStep>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A Boolean specifying that the step specified by **restartStep** should be "
"terminated at the increment specified by **restartIncrement**."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`shellToSolid <abaqus.Model.ModelBase.ModelBase.shellToSolid>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A Boolean specifying that a shell global model drives a solid submodel."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`lastChangedCount "
"<abaqus.Model.ModelBase.ModelBase.lastChangedCount>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A Float specifying the time stamp that indicates when the model was last "
"changed."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`description <abaqus.Model.ModelBase.ModelBase.description>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A String specifying the purpose and contents of the Model object."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`restartJob <abaqus.Model.ModelBase.ModelBase.restartJob>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A String specifying the name of the job that generated the restart data."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`restartStep <abaqus.Model.ModelBase.ModelBase.restartStep>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A String specifying the name of the step where the restart analysis will "
"start."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`globalJob <abaqus.Model.ModelBase.ModelBase.globalJob>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A String specifying the name of the job that generated the results for the"
" global model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`copyConstraints "
"<abaqus.Model.ModelBase.ModelBase.copyConstraints>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A boolean specifying the status of constraints created in a model, in the "
"model which instances this model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`copyConnectors "
"<abaqus.Model.ModelBase.ModelBase.copyConnectors>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A boolean specifying the status of connectors created in a model, in the "
"model which instances this model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`copyInteractions "
"<abaqus.Model.ModelBase.ModelBase.copyInteractions>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A boolean specifying the status of interactions created in a model, in the"
" model which instances this model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`keywordBlock <abaqus.Model.ModelBase.ModelBase.keywordBlock>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A KeywordBlock object."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`rootAssembly <abaqus.Model.ModelBase.ModelBase.rootAssembly>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "An Assembly object."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`amplitudes <abaqus.Model.ModelBase.ModelBase.amplitudes>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1 ../../None:52:<autosummary>:1
msgid "A repository of Amplitude objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`profiles <abaqus.Model.ModelBase.ModelBase.profiles>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1 ../../None:52:<autosummary>:1
msgid "A repository of Profile objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`boundaryConditions "
"<abaqus.Model.ModelBase.ModelBase.boundaryConditions>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of BoundaryCondition objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`constraints <abaqus.Model.ModelBase.ModelBase.constraints>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of ConstrainedSketchConstraint objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`analyticalFields "
"<abaqus.Model.ModelBase.ModelBase.analyticalFields>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of AnalyticalField objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`discreteFields "
"<abaqus.Model.ModelBase.ModelBase.discreteFields>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of DiscreteField objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`predefinedFields "
"<abaqus.Model.ModelBase.ModelBase.predefinedFields>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of PredefinedField objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`interactions <abaqus.Model.ModelBase.ModelBase.interactions>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of Interaction objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`interactionProperties "
"<abaqus.Model.ModelBase.ModelBase.interactionProperties>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of InteractionProperty objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`contactControls "
"<abaqus.Model.ModelBase.ModelBase.contactControls>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of ContactControl objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`contactInitializations "
"<abaqus.Model.ModelBase.ModelBase.contactInitializations>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of ContactInitialization objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`contactStabilizations "
"<abaqus.Model.ModelBase.ModelBase.contactStabilizations>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of ContactStabilization objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`linkedInstances "
"<abaqus.Model.ModelBase.ModelBase.linkedInstances>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A tuple of tuples of Strings specifying the linked child PartInstance name"
" in the current model to the corresponding parent PartInstance name in a "
"different model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`linkedParts <abaqus.Model.ModelBase.ModelBase.linkedParts>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
"A tuple of tuples of Strings specifying the linked child Part name in the "
"current model to the corresponding parent Part name in a different model."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`loads <abaqus.Model.ModelBase.ModelBase.loads>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of Load objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`materials <abaqus.Model.ModelBase.ModelBase.materials>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1 ../../None:52:<autosummary>:1
msgid "A repository of Material objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`calibrations <abaqus.Model.ModelBase.ModelBase.calibrations>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of Calibration objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`sections <abaqus.Model.ModelBase.ModelBase.sections>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1 ../../None:52:<autosummary>:1
msgid "A repository of Section objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`remeshingRules "
"<abaqus.Model.ModelBase.ModelBase.remeshingRules>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of RemeshingRule objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`sketches <abaqus.Model.ModelBase.ModelBase.sketches>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of ConstrainedSketch objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`parts <abaqus.Model.ModelBase.ModelBase.parts>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of Part objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`steps <abaqus.Model.ModelBase.ModelBase.steps>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of Step objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`featureOptions "
"<abaqus.Model.ModelBase.ModelBase.featureOptions>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A FeatureOptions object."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`adaptiveMeshConstraints "
"<abaqus.Model.ModelBase.ModelBase.adaptiveMeshConstraints>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of AdaptiveMeshConstraint objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`adaptiveMeshControls "
"<abaqus.Model.ModelBase.ModelBase.adaptiveMeshControls>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of AdaptiveMeshControl objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`timePoints <abaqus.Model.ModelBase.ModelBase.timePoints>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of TimePoint objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ":py:obj:`filters <abaqus.Model.ModelBase.ModelBase.filters>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1 ../../None:52:<autosummary>:1
msgid "A repository of Filter objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`integratedOutputSections "
"<abaqus.Model.ModelBase.ModelBase.integratedOutputSections>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of IntegratedOutputSection objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`fieldOutputRequests "
"<abaqus.Model.ModelBase.ModelBase.fieldOutputRequests>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of FieldOutputRequest objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`historyOutputRequests "
"<abaqus.Model.ModelBase.ModelBase.historyOutputRequests>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of HistoryOutputRequest objects."
msgstr ""

#: ../../None:52:<autosummary>:1
msgid ""
":py:obj:`optimizationTasks "
"<abaqus.Model.ModelBase.ModelBase.optimizationTasks>`\\"
msgstr ""

#: ../../None:52:<autosummary>:1
msgid "A repository of OptimizationTask objects."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb of
msgid "Public Methods:"
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`beamProfilesFromOdb <abaqus.BeamSectionProfile.BeamSectionProfile"
"Model.BeamSectionProfileModel.beamProfilesFromOdb>`\\ \\(fileName\\)"
msgstr ""

#: ../../None:14:<autosummary>:1
msgid "This method creates Profile objects by reading an output database."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`ArbitraryProfile <abaqus.BeamSectionProfile.BeamSectionProfileMod"
"el.BeamSectionProfileModel.ArbitraryProfile>`\\ \\(name\\, table\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:31
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:1
#: of
msgid "This method creates a ArbitraryProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`BoxProfile <abaqus.BeamSectionProfile.BeamSectionProfileModel.Bea"
"mSectionProfileModel.BoxProfile>`\\ \\(name\\, a\\, b\\, "
"uniformThickness\\, t1\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:1
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:19 of
msgid "This method creates a BoxProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`CircularProfile <abaqus.BeamSectionProfile.BeamSectionProfileMode"
"l.BeamSectionProfileModel.CircularProfile>`\\ \\(name\\, r\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:1
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:19 of
msgid "This method creates a CircularProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`GeneralizedProfile <abaqus.BeamSectionProfile.BeamSectionProfileM"
"odel.BeamSectionProfileModel.GeneralizedProfile>`\\ \\(name\\, area\\, "
"i11\\, i12\\, ...\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:1
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:20 of
msgid "This method creates a GeneralizedProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`HexagonalProfile <abaqus.BeamSectionProfile.BeamSectionProfileMod"
"el.BeamSectionProfileModel.HexagonalProfile>`\\ \\(name\\, r\\, t\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:1
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:19 of
msgid "This method creates a HexagonalProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`IProfile <abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamS"
"ectionProfileModel.IProfile>`\\ \\(name\\, l\\, h\\, b1\\, b2\\, t1\\, "
"t2\\, t3\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:1
#: abaqus.BeamSectionProfile.IProfile.IProfile:19 of
msgid "This method creates an IProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`LProfile <abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamS"
"ectionProfileModel.LProfile>`\\ \\(name\\, a\\, b\\, t1\\, t2\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:1
#: abaqus.BeamSectionProfile.LProfile.LProfile:19 of
msgid "This method creates a LProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`PipeProfile <abaqus.BeamSectionProfile.BeamSectionProfileModel.Be"
"amSectionProfileModel.PipeProfile>`\\ \\(name\\, r\\, t\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:1
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:19 of
msgid "This method creates a PipeProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`RectangularProfile <abaqus.BeamSectionProfile.BeamSectionProfileM"
"odel.BeamSectionProfileModel.RectangularProfile>`\\ \\(name\\, a\\, b\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:1
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:19 of
msgid "This method creates a RectangularProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`TProfile <abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamS"
"ectionProfileModel.TProfile>`\\ \\(name\\, b\\, h\\, l\\, tf\\, tw\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:1
#: abaqus.BeamSectionProfile.TProfile.TProfile:19 of
msgid "This method creates a TProfile object."
msgstr ""

#: ../../None:14:<autosummary>:1
msgid ""
":py:obj:`TrapezoidalProfile <abaqus.BeamSectionProfile.BeamSectionProfileM"
"odel.BeamSectionProfileModel.TrapezoidalProfile>`\\ \\(name\\, a\\, b\\, "
"c\\, d\\)"
msgstr ""

#: ../../None:13:<autosummary>:1 ../../None:14:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:1
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:19 of
msgid "This method creates a TrapezoidalProfile object."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`__init__ <abaqus.Model.ModelBase.ModelBase.__init__>`\\ "
"\\(name\\[\\, description\\, ...\\]\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`ModelFromInputFile "
"<abaqus.Model.ModelBase.ModelBase.ModelFromInputFile>`\\ \\(name\\, "
"inputFileName\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
"This method creates a Model object by reading the keywords in an input "
"file and creating the corresponding Abaqus/CAE objects."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`ModelFromOdbFile "
"<abaqus.Model.ModelBase.ModelBase.ModelFromOdbFile>`\\ \\(name\\, "
"odbFileName\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
"This method creates a Model object by reading an output database and "
"creating any corresponding Abaqus/CAE objects."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`ModelFromNastranFile "
"<abaqus.Model.ModelBase.ModelBase.ModelFromNastranFile>`\\ \\(modelName\\,"
" inputFileName\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
"This method creates a Model object by reading the keywords in a Nastran "
"bulk data file or Nastran input file and creating any corresponding "
"Abaqus/CAE objects."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`setValues <abaqus.Model.ModelBase.ModelBase.setValues>`\\ "
"\\(\\[description\\, noPartsInputFile\\, ...\\]\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid "This method modifies the Model object."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:1
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:1
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:1
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:1
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:1
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:1
#: abaqus.BeamSectionProfile.IProfile.IProfile:1
#: abaqus.BeamSectionProfile.LProfile.LProfile:1
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:1
#: abaqus.BeamSectionProfile.Profile.Profile:1
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:1
#: abaqus.BeamSectionProfile.TProfile.TProfile:1
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:1 of
msgid "Member Details:"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:29
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:10
#: of
msgid ""
"Check `ArbitraryProfile on help.3ds.com/2016 <https://help.3ds.com/2016/En"
"glish/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"arbitraryprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:42
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.ArbitraryProfile.table:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:15
#: of
msgid ""
"A sequence of sequences of Floats specifying the items described below."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:44
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:17
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:17
#: of
msgid "An ArbitraryProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:45
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile:18
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile:18
#: of
msgid ":class:`ArbitraryProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile
#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile.setValues
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.ArbitraryProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile.setValues
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.setValues
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile.setValues
#: abaqus.BeamSectionProfile.IProfile.IProfile
#: abaqus.BeamSectionProfile.IProfile.IProfile.setValues
#: abaqus.BeamSectionProfile.LProfile.LProfile
#: abaqus.BeamSectionProfile.LProfile.LProfile.setValues
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile.setValues
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile.setValues
#: abaqus.BeamSectionProfile.TProfile.TProfile
#: abaqus.BeamSectionProfile.TProfile.TProfile.setValues
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.setValues of
msgid "Raises"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:10
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:17 of
msgid ""
"Check `BoxProfile on help.3ds.com/2016 <https://help.3ds.com/2016/English/"
"DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"boxprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:15
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:30
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.a:1 of
msgid ""
"A Float specifying the **a** dimension of the box profile. For more "
"information, see [Beam cross-section library](https://help.3ds.com/2021/En"
"glish/DSSIMULIA_Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:19
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:34
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.b:1 of
msgid "A Float specifying the **b** dimension of the box profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:21
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:36
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.uniformThickness:1 of
msgid "A Boolean specifying whether the thickness is uniform."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:23
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:23
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:38
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.t1:1 of
msgid ""
"A Float specifying the uniform wall thickness if **uniformThickness** = "
"ON, and the wall thickness of the first segment if **uniformThickness** = "
"OFF."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:26
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:26
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:41
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues:7
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.t2:1 of
msgid ""
"A Float specifying the wall thickness of the second segment. **t2** is "
"required only when **uniformThickness** = OFF. The default value is 0.0."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:29
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:29
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:44
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues:10
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.t3:1 of
msgid ""
"A Float specifying the wall thickness of the third segment. **t3** is "
"required only when **uniformThickness** = OFF. The default value is 0.0."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:32
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:32
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:47
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues:13
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.t4:1 of
msgid ""
"A Float specifying the wall thickness of the fourth segment. **t4** is "
"required only when **uniformThickness** = OFF. The default value is 0.0."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:35
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:35
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:50 of
msgid "A BoxProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.BoxProfile:36
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.BoxProfile:36
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:51 of
msgid ":class:`BoxProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:10
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:17 of
msgid ""
"Check `CircularProfile on help.3ds.com/2016 <https://help.3ds.com/2016/Eng"
"lish/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"circularprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:15
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:30
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile.r:1 of
msgid ""
"A positive Float specifying the **r** dimension (outer radius) of the "
"circular profile. For more information, see [Beam cross-section library](h"
"ttps://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/si"
"maelm-c-beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:19
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:34 of
msgid "A CircularProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.CircularProfile:20
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.CircularProfile:20
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:35 of
msgid ":class:`CircularProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:10
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:18 of
msgid ""
"Check `GeneralizedProfile on help.3ds.com/2016 <https://help.3ds.com/2016/"
"English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"generalizedprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:15
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:31
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.area:1 of
msgid "A Float specifying the cross-sectional area for the profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:17
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:17
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:33
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.i11:1 of
msgid ""
"A Float specifying the moment of inertia for bending about the 1-axis, "
"I11I11."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:19
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:35
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.i12:1 of
msgid "A Float specifying the moment of inertia for cross bending, I12I12."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:21
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:37
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.i22:1 of
msgid ""
"A Float specifying the moment of inertia for bending about the 2-axis, "
"I22I22."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:23
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:23
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:39
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.j:1 of
msgid "A Float specifying the torsional constant, JJ."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:25
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:25
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:41
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.gammaO:1 of
msgid "A Float specifying the sectorial moment, Γ0Γ0."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:27
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:27
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:43
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.gammaW:1 of
msgid "A Float specifying the warping constant, ΓWΓW."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:29
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:29
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:45 of
msgid "A GeneralizedProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.GeneralizedProfile:30
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.GeneralizedProfile:30
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:46 of
msgid ":class:`GeneralizedProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:10
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:17 of
msgid ""
"Check `HexagonalProfile on help.3ds.com/2016 <https://help.3ds.com/2016/En"
"glish/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"hexagonalprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:15
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:30
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile.r:1 of
msgid ""
"A positive Float specifying the **r** dimension (outer radius) of the "
"hexagonal profile. For more information, see [Beam cross-section library]("
"https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/s"
"imaelm-c-beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:19
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:34
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile.t:1 of
msgid ""
"A positive Float specifying the **t** dimension (wall thickness) of the "
"hexagonal profile, *t < (sqrt(3)/2)r*."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:22
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:22
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:37 of
msgid "A HexagonalProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.HexagonalProfile:23
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.HexagonalProfile:23
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:38 of
msgid ":class:`HexagonalProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:10
#: abaqus.BeamSectionProfile.IProfile.IProfile:17 of
msgid ""
"Check `IProfile on help.3ds.com/2016 <https://help.3ds.com/2016/English/DS"
"SIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"iprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:15
#: abaqus.BeamSectionProfile.IProfile.IProfile:30
#: abaqus.BeamSectionProfile.IProfile.IProfile.l:1 of
msgid ""
"A Float specifying the **l** dimension (offset of 1-axis from the bottom "
"flange surface) of the I profile. For more information, see [Beam cross-"
"section library](https://help.3ds.com/2021/English/DSSIMULIA_Established/S"
"IMACAEELMRefMap/simaelm-c-beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:19
#: abaqus.BeamSectionProfile.IProfile.IProfile:34
#: abaqus.BeamSectionProfile.IProfile.IProfile.h:1 of
msgid "A Float specifying the **h** dimension (height) of the I profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:21
#: abaqus.BeamSectionProfile.IProfile.IProfile:36
#: abaqus.BeamSectionProfile.IProfile.IProfile.b1:1 of
msgid ""
"A Float specifying the **b1** dimension (bottom flange width) of the I "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:23
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:23
#: abaqus.BeamSectionProfile.IProfile.IProfile:38
#: abaqus.BeamSectionProfile.IProfile.IProfile.b2:1 of
msgid ""
"A Float specifying the **b2** dimension (top flange width) of the I "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:25
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:25
#: abaqus.BeamSectionProfile.IProfile.IProfile:40
#: abaqus.BeamSectionProfile.IProfile.IProfile.t1:1 of
msgid ""
"A Float specifying the **t1** dimension (bottom flange thickness) of the I"
" profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:27
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:27
#: abaqus.BeamSectionProfile.IProfile.IProfile:42
#: abaqus.BeamSectionProfile.IProfile.IProfile.t2:1 of
msgid ""
"A Float specifying the **t2** dimension (top flange thickness) of the I "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:29
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:29
#: abaqus.BeamSectionProfile.IProfile.IProfile:44
#: abaqus.BeamSectionProfile.IProfile.IProfile.t3:1 of
msgid ""
"A Float specifying the **t3** dimension (web thickness) of the I profile."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:31
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:31
#: abaqus.BeamSectionProfile.IProfile.IProfile:46 of
msgid "An IProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.IProfile:32
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.IProfile:32
#: abaqus.BeamSectionProfile.IProfile.IProfile:47 of
msgid ":class:`IProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:10
#: abaqus.BeamSectionProfile.LProfile.LProfile:17 of
msgid ""
"Check `LProfile on help.3ds.com/2016 <https://help.3ds.com/2016/English/DS"
"SIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"lprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:15
#: abaqus.BeamSectionProfile.LProfile.LProfile:30
#: abaqus.BeamSectionProfile.LProfile.LProfile.a:1 of
msgid ""
"A positive Float specifying the **a** dimension (flange length) of the L "
"profile. For more information, see [Beam cross-section library](https://he"
"lp.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:19
#: abaqus.BeamSectionProfile.LProfile.LProfile:34
#: abaqus.BeamSectionProfile.LProfile.LProfile.b:1 of
msgid ""
"A positive Float specifying the **b** dimension (flange length) of the L "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:21
#: abaqus.BeamSectionProfile.LProfile.LProfile:36
#: abaqus.BeamSectionProfile.LProfile.LProfile.t1:1 of
msgid ""
"A positive Float specifying the **t1** dimension (flange thickness) of the"
" L profile (*t1 < b*)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:24
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:24
#: abaqus.BeamSectionProfile.LProfile.LProfile:39
#: abaqus.BeamSectionProfile.LProfile.LProfile.t2:1 of
msgid ""
"A positive Float specifying the **t2** dimension (flange thickness) of the"
" L profile (*t2< a*)."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:27
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:27
#: abaqus.BeamSectionProfile.LProfile.LProfile:42 of
msgid "A LProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.LProfile:28
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.LProfile:28
#: abaqus.BeamSectionProfile.LProfile.LProfile:43 of
msgid ":class:`LProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:10
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:17 of
msgid ""
"Check `PipeProfile on help.3ds.com/2016 <https://help.3ds.com/2016/English"
"/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"pipeprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:15
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:30
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile.r:1 of
msgid ""
"A Float specifying the outer radius of the pipe. For more information, see"
" [Beam cross-section library](https://help.3ds.com/2021/English/DSSIMULIA_"
"Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:19
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:34
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile.t:1 of
msgid "A Float specifying the wall thickness of the pipe."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:21
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:36 of
msgid "A PipeProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.PipeProfile:22
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.PipeProfile:22
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:37 of
msgid ":class:`PipeProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:10
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:17 of
msgid ""
"Check `RectangularProfile on help.3ds.com/2016 <https://help.3ds.com/2016/"
"English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"rectangularprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:15
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:30
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile.a:1 of
msgid ""
"A positive Float specifying the **a** dimension of the rectangular "
"profile. For more information, see [Beam cross-section library](https://he"
"lp.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:19
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:34
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile.b:1 of
msgid ""
"A positive Float specifying the **b** dimension of the rectangular "
"profile."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:21
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:36 of
msgid "A RectangularProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.RectangularProfile:22
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.RectangularProfile:22
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:37 of
msgid ":class:`RectangularProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:10
#: abaqus.BeamSectionProfile.TProfile.TProfile:17 of
msgid ""
"Check `TProfile on help.3ds.com/2016 <https://help.3ds.com/2016/English/DS"
"SIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"tprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:15
#: abaqus.BeamSectionProfile.TProfile.TProfile:30
#: abaqus.BeamSectionProfile.TProfile.TProfile.b:1 of
msgid ""
"A positive Float specifying the **b** dimension (flange width) of the T "
"profile. For more information, see [Beam cross-section library](https://he"
"lp.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:19
#: abaqus.BeamSectionProfile.TProfile.TProfile:34
#: abaqus.BeamSectionProfile.TProfile.TProfile.h:1 of
msgid ""
"A positive Float specifying the **h** dimension (height) of the T profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:21
#: abaqus.BeamSectionProfile.TProfile.TProfile:36
#: abaqus.BeamSectionProfile.TProfile.TProfile.l:1 of
msgid ""
"A positive Float specifying the **l** dimension (offset of 1-axis from the"
" edge of web) of the T profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:24
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:24
#: abaqus.BeamSectionProfile.TProfile.TProfile:39
#: abaqus.BeamSectionProfile.TProfile.TProfile.tf:1 of
msgid ""
"A positive Float specifying the **tf** dimension (flange thickness) of the"
" T profile (*tf < h*)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:27
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:27
#: abaqus.BeamSectionProfile.TProfile.TProfile:42
#: abaqus.BeamSectionProfile.TProfile.TProfile.tw:1 of
msgid ""
"A positive Float specifying the **tw** dimension (web thickness) of the T "
"profile (*tw< b*)."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:30
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:30
#: abaqus.BeamSectionProfile.TProfile.TProfile:45 of
msgid "A TProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TProfile:31
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TProfile:31
#: abaqus.BeamSectionProfile.TProfile.TProfile:46 of
msgid ":class:`TProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:10
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:10
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:17 of
msgid ""
"Check `TrapezoidalProfile on help.3ds.com/2016 <https://help.3ds.com/2016/"
"English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"trapezoidalprofilepyc.htm?contextscope=all>`__."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:15
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:15
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:30
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.a:1 of
msgid ""
"A positive Float specifying the **a** dimension of the Trapezoidal "
"profile. For more information, see [Beam cross-section library](https://he"
"lp.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEELMRefMap/simaelm-c-"
"beamcrosssectlib.htm?ContextScope=all)."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:19
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:19
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:34
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.b:1 of
msgid ""
"A positive Float specifying the **b** dimension of the Trapezoidal "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:21
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:21
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:36
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.c:1 of
msgid ""
"A positive Float specifying the **c** dimension of the Trapezoidal "
"profile."
msgstr ""

#: ../../docstring
#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:23
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:23
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:38
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.d:1 of
msgid "A Float specifying the **d** dimension of the Trapezoidal profile."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:25
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:25
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:40 of
msgid "A TrapezoidalProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.TrapezoidalProfile:26
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb.TrapezoidalProfile:26
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:41 of
msgid ":class:`TrapezoidalProfile`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:1
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:1 of
msgid ""
"This method creates Profile objects by reading an output database. The new"
" profiles are placed in the profiles repository."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:10
#: of
msgid ""
"Check `BeamSectionProfileModel.beamProfilesFromOdb on help.3ds.com/2016 <h"
"ttps://help.3ds.com/2016/English/DSSIMULIA_Established/SIMACAEKERRefMap/si"
"maker-c-modelpyc.htm?contextscope=all#simaker-"
"modelbeamprofilesfromodbpyc>`__."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:13
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:13 of
msgid ""
"A String specifying the name of the output database file (including the "
".odb extension) to be read. The String can also be the full path to the "
"output database file if it is located in another directory."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:17
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:17 of
msgid "A list of Profile objects."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileModel.BeamSectionProfileModel.beamProfilesFromOdb:18
#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:18 of
msgid ":class:`List[Profile]`"
msgstr ""

#: ../../reference/mdb/model/profile.md:17
msgid "In Odb"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:1 of
msgid "Bases: :py:class:`~abaqus.Odb.OdbBase.OdbBase`"
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:1 of
msgid ""
"The Odb object is the in-memory representation of an output database (ODB)"
" file."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:10 of
msgid ""
"Check `BeamSectionProfileOdb on help.3ds.com/2016 <https://help.3ds.com/20"
"16/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"odbpyc.htm?contextscope=all>`__."
msgstr ""

#: ../../None:7:<autosummary>:1
#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:12 of
msgid "This method creates a new Odb object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:22 of
msgid ""
"A String specifying the title of the output database. The default value is"
" an empty string."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:25 of
msgid ""
"A String specifying the description of the output database. The default "
"value is an empty string."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:28 of
msgid ""
"A String specifying the path to the file where the new output database "
"(.odb ) file will be written. The default value is an empty string."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:31 of
msgid "An Odb object."
msgstr ""

#: abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSectionProfileOdb:32 of
msgid ":class:`Odb`"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`isReadOnly <abaqus.Odb.OdbBase.OdbBase.isReadOnly>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ""
"A Boolean specifying whether the output database was opened with read-only"
" access."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`amplitudes <abaqus.Odb.OdbBase.OdbBase.amplitudes>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`filters <abaqus.Odb.OdbBase.OdbBase.filters>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`rootAssembly <abaqus.Odb.OdbBase.OdbBase.rootAssembly>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "An OdbAssembly object."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`jobData <abaqus.Odb.OdbBase.OdbBase.jobData>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A JobData object."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`parts <abaqus.Odb.OdbBase.OdbBase.parts>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A repository of OdbPart objects."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`materials <abaqus.Odb.OdbBase.OdbBase.materials>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`steps <abaqus.Odb.OdbBase.OdbBase.steps>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A repository of OdbStep objects."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`sections <abaqus.Odb.OdbBase.OdbBase.sections>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ""
":py:obj:`sectionCategories "
"<abaqus.Odb.OdbBase.OdbBase.sectionCategories>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A repository of SectionCategory objects."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ""
":py:obj:`sectorDefinition <abaqus.Odb.OdbBase.OdbBase.sectorDefinition>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A SectorDefinition object."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`userData <abaqus.Odb.OdbBase.OdbBase.userData>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A UserData object."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`customData <abaqus.Odb.OdbBase.OdbBase.customData>`\\"
msgstr ""

#: ../../None:16:<autosummary>:1
msgid "A RepositorySupport object."
msgstr ""

#: ../../None:16:<autosummary>:1
msgid ":py:obj:`profiles <abaqus.Odb.OdbBase.OdbBase.profiles>`\\"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`ArbitraryProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb"
".BeamSectionProfileOdb.ArbitraryProfile>`\\ \\(name\\, table\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`BoxProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamS"
"ectionProfileOdb.BoxProfile>`\\ \\(name\\, a\\, b\\, uniformThickness\\, "
"t1\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`CircularProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb."
"BeamSectionProfileOdb.CircularProfile>`\\ \\(name\\, r\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`GeneralizedProfile <abaqus.BeamSectionProfile.BeamSectionProfileO"
"db.BeamSectionProfileOdb.GeneralizedProfile>`\\ \\(name\\, area\\, i11\\, "
"i12\\, ...\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`HexagonalProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb"
".BeamSectionProfileOdb.HexagonalProfile>`\\ \\(name\\, r\\, t\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`IProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSec"
"tionProfileOdb.IProfile>`\\ \\(name\\, l\\, h\\, b1\\, b2\\, t1\\, t2\\, "
"t3\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`LProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSec"
"tionProfileOdb.LProfile>`\\ \\(name\\, a\\, b\\, t1\\, t2\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`PipeProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb.Beam"
"SectionProfileOdb.PipeProfile>`\\ \\(name\\, r\\, t\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`RectangularProfile <abaqus.BeamSectionProfile.BeamSectionProfileO"
"db.BeamSectionProfileOdb.RectangularProfile>`\\ \\(name\\, a\\, b\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`TProfile <abaqus.BeamSectionProfile.BeamSectionProfileOdb.BeamSec"
"tionProfileOdb.TProfile>`\\ \\(name\\, b\\, h\\, l\\, tf\\, tw\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ""
":py:obj:`TrapezoidalProfile <abaqus.BeamSectionProfile.BeamSectionProfileO"
"db.BeamSectionProfileOdb.TrapezoidalProfile>`\\ \\(name\\, a\\, b\\, c\\, "
"d\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`__init__ <abaqus.Odb.OdbBase.OdbBase.__init__>`\\ \\(name\\[\\, "
"analysisTitle\\, description\\, ...\\]\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ":py:obj:`close <abaqus.Odb.OdbBase.OdbBase.close>`\\ \\(\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid "This method closes an output database."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
":py:obj:`getFrame <abaqus.Odb.OdbBase.OdbBase.getFrame>`\\ "
"\\(frameValue\\[\\, match\\]\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
"This method returns the frame at the specified time, frequency, or mode."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ":py:obj:`save <abaqus.Odb.OdbBase.OdbBase.save>`\\ \\(\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid "This method saves output to an output database (.odb ) file."
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ":py:obj:`update <abaqus.Odb.OdbBase.OdbBase.update>`\\ \\(\\)"
msgstr ""

#: ../../None:7:<autosummary>:1
msgid ""
"This method is used to update an Odb object in memory while an Abaqus "
"analysis writes data to the associated output database."
msgstr ""

#: ../../reference/mdb/model/profile.md:28
msgid "Other Classes"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:1
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:1
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:1
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:1
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:1
#: abaqus.BeamSectionProfile.IProfile.IProfile:1
#: abaqus.BeamSectionProfile.LProfile.LProfile:1
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:1
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:1
#: abaqus.BeamSectionProfile.TProfile.TProfile:1
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:1 of
msgid "Bases: :py:class:`~abaqus.BeamSectionProfile.Profile.Profile`"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:1 of
msgid ""
"The ArbitraryProfile object defines the properties of an arbitrary "
"profile. The ArbitraryProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:12 of
msgid ""
"The table data for this object are: The first sequence in the table "
"specifies the following:"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:15 of
msgid "1-coordinate of the first point defining the profile."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:16 of
msgid "2-coordinate of the first point defining the profile."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:18 of
msgid "All other sequences in the table specify the following:"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:20 of
msgid "1-coordinate of the next point defining the profile."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:21 of
msgid "2-coordinate of the next point defining the profile."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:22 of
msgid "The thickness of the segment ending at that point."
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:24
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:12
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:12
#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:13
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:12
#: abaqus.BeamSectionProfile.IProfile.IProfile:12
#: abaqus.BeamSectionProfile.LProfile.LProfile:12
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:12
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:12
#: abaqus.BeamSectionProfile.TProfile.TProfile:12
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:12 of
msgid "The corresponding analysis keywords are:"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile:26
#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:14
#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:14
#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:14
#: abaqus.BeamSectionProfile.IProfile.IProfile:14
#: abaqus.BeamSectionProfile.LProfile.LProfile:14
#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:14
#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:14
#: abaqus.BeamSectionProfile.TProfile.TProfile:14
#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:14 of
msgid "BEAM SECTION"
msgstr ""

#: abaqus.BeamSectionProfile.ArbitraryProfile.ArbitraryProfile.setValues:1 of
msgid "This method modifies the ArbitraryProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.Profile.Profile:1 of
msgid "Bases: :py:class:`object`"
msgstr ""

#: abaqus.BeamSectionProfile.Profile.Profile:1 of
msgid ""
"The Profile object defines the geometrical properties of a beam cross-"
"section. Profile is an abstract base type."
msgstr ""

#: abaqus.BeamSectionProfile.Profile.Profile:13 of
msgid ""
"Check `Profile on help.3ds.com/2016 <https://help.3ds.com/2016/English/DSS"
"IMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"profilepyc.htm?contextscope=all>`__."
msgstr ""

#: abaqus.BeamSectionProfile.Profile.Profile.beamProfilesFromOdb:10 of
msgid ""
"Check `Profile.beamProfilesFromOdb on help.3ds.com/2016 <https://help.3ds."
"com/2016/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"profilepyc.htm?contextscope=all#simaker-profilebeamprofilesfromodbpyc>`__."
msgstr ""

#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile:1 of
msgid ""
"The BoxProfile object defines the properties of a box profile. The "
"BoxProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues:1 of
msgid "This method modifies the BoxProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.BoxProfile.BoxProfile.setValues:4 of
msgid ""
"Check `BoxProfile.setValues on help.3ds.com/2016 <https://help.3ds.com/201"
"6/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-"
"boxprofilepyc.htm?contextscope=all#simaker-boxprofilesetvaluespyc>`__."
msgstr ""

#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile:1 of
msgid ""
"The CircularProfile object defines the properties of a solid circular "
"profile. The CircularProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.CircularProfile.CircularProfile.setValues:1 of
msgid "This method modifies the CircularProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:1 of
msgid ""
"The GeneralizedProfile object defines the properties of a profile via its "
"area, moment of inertia, etc. The GeneralizedProfile object is derived "
"from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile:15 of
msgid "BEAM GENERAL SECTION"
msgstr ""

#: abaqus.BeamSectionProfile.GeneralizedProfile.GeneralizedProfile.setValues:1
#: of
msgid "This method modifies the GeneralizedProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile:1 of
msgid ""
"The HexagonalProfile object defines the properties of a hexagonal profile."
" The HexagonalProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.HexagonalProfile.HexagonalProfile.setValues:1 of
msgid "This method modifies the HexagonalProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.IProfile.IProfile:1 of
msgid ""
"The IProfile object defines the properties of an I profile. The IProfile "
"object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.IProfile.IProfile.setValues:1 of
msgid "This method modifies the IProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.LProfile.LProfile:1 of
msgid ""
"The LProfile object defines the properties of a L profile. The LProfile "
"object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.LProfile.LProfile.setValues:1 of
msgid "This method modifies the LProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile:1 of
msgid ""
"The PipeProfile object defines the properties of a circular pipe profile. "
"The PipeProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.PipeProfile.PipeProfile.setValues:1 of
msgid "This method modifies the PipeProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile:1 of
msgid ""
"The RectangularProfile object defines the properties of a solid "
"rectangular profile. The RectangularProfile object is derived from the "
"Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.RectangularProfile.RectangularProfile.setValues:1
#: of
msgid "This method modifies the RectangularProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.TProfile.TProfile:1 of
msgid ""
"The TProfile object defines the properties of a T profile. The TProfile "
"object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.TProfile.TProfile.setValues:1 of
msgid "This method modifies the TProfile object."
msgstr ""

#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile:1 of
msgid ""
"The TrapezoidalProfile object defines the properties of a trapezoidal "
"profile. The TrapezoidalProfile object is derived from the Profile object."
msgstr ""

#: abaqus.BeamSectionProfile.TrapezoidalProfile.TrapezoidalProfile.setValues:1
#: of
msgid "This method modifies the TrapezoidalProfile object."
msgstr ""

